const {chromium,webkit}=require('playwright');const assert=require('node:assert/strict');const http=require('node:http');const fs=require('node:fs');const path=require('node:path');
(async()=>{const root=process.env.WEB_ROOT||path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+'/')){res.writeHead(403).end();return}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(data)});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await (process.env.BROWSER_ENGINE==='webkit'?webkit:chromium).launch();const page=await browser.newPage({viewport:{width:390,height:844}});await page.addInitScript(()=>localStorage.setItem('voxxly_web_access_token','fixture'));let admin=true,failReply=true,messages=[],lastRequestId,replyCount=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));const ticket={id:1,status:'OPEN',category:'OTHER',message:'<img src=x onerror=alert(1)> My upload is stuck.',createdAt:new Date().toISOString()};
await page.route('https://dev-backend-withered-thunder-4589.fly.dev/**',async route=>{const url=new URL(route.request().url());const method=route.request().method();let body=[],status=200;
if(url.pathname==='/auth/me')body={id:1,username:'dave',email:'admin@example.test'};
else if(url.pathname==='/me/support-access')body={admin};
else if(url.pathname==='/admin/support/tickets')body=[ticket];
else if(url.pathname==='/admin/reports/clips')body=[{id:2,status:'PENDING',clipId:99,reason:'OTHER',details:'Reported video',createdAt:ticket.createdAt}];
else if(url.pathname==='/admin/reports/users')body=[];
else if(url.pathname==='/admin/inbox/SUPPORT/1/messages'){if(method==='POST'){const p=JSON.parse(route.request().postData());replyCount++;if(lastRequestId)assert.equal(p.requestId,lastRequestId);lastRequestId=p.requestId;if(failReply){status=500;body={message:'offline'}}else{messages.push({id:2,body:p.body,incoming:false,createdAt:ticket.createdAt});body=messages.at(-1)}}else body={email:'customer@example.test',messages};}
else if(url.pathname==='/admin/support/tickets/1'&&method==='PATCH'){ticket.status=JSON.parse(route.request().postData()).status;body=ticket;}
await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});});
const origin=process.env.TEST_BASE_URL||`http://127.0.0.1:${server.address().port}`;await page.goto(origin+'/#/settings');await page.getByRole('link',{name:'Support inbox',exact:true}).click();await page.getByRole('button',{name:/Support #1/}).click();await page.getByLabel('Reply',{exact:true}).fill('We can help with this.');assert.equal(await page.locator('.inbox-messages img').count(),0);
await page.getByRole('button',{name:'Refresh',exact:true}).click();assert.equal(await page.getByLabel('Reply',{exact:true}).inputValue(),'We can help with this.');
await page.getByRole('button',{name:'Send reply',exact:true}).click();await page.getByText('Couldn’t queue reply. Your draft is saved.').waitFor();assert.equal(await page.getByLabel('Reply',{exact:true}).inputValue(),'We can help with this.');failReply=false;await page.getByRole('button',{name:'Send reply',exact:true}).click();await page.locator('.inbox-message.is-reply').waitFor();assert.equal(replyCount,2);assert.equal(messages.length,1);
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'no horizontal overflow '+width);}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/private/tmp/voxxly-support-work/inbox-mobile.png',fullPage:true});await page.getByRole('button',{name:'Resolve',exact:true}).click();await page.getByRole('button',{name:'Resolved',exact:true}).click();await page.getByRole('button',{name:/Support #1/}).click();await page.getByRole('button',{name:'Reopen',exact:true}).waitFor();
admin=false;await page.goto(origin+'/#/admin/support');await page.reload();await page.getByRole('heading',{name:'Administrators only',exact:true}).waitFor();assert.equal(await page.locator('.inbox-list').count(),0);assert.deepEqual(errors,[]);console.log('PASS: admin navigation, role gate, escaped content, responsive layout, draft preservation, idempotent retry, resolve/reopen.');
}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
